services:
  kafka-mb:
    image: apache/kafka:4.1.1
    container_name: kafka-kraft
    ports:
      - "29092:29092"  # external
      - "29093:29093"  # controller
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # INTERNAL + EXTERNAL
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-kraft:9092,EXTERNAL://localhost:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:29093

      KAFKA_CLUSTER_ID: QYr03I4hQuuQf4q5OgS1Fg

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    volumes:
       - kafka_data:/var/lib/kafka/data


    networks:
      - saga-net   

  booking-service-db:
    image: postgres:17.5-bullseye
    container_name: booking-service-db
    environment:
      POSTGRES_USER: itpusr
      POSTGRES_PASSWORD: itp@168
      DATABASE_NAME: bookingdb
    ports:
      - "5432:5432"
    volumes:
      - ./init_scripts/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
      - booking-service-postgres-vol:/var/lib/postgresql/data
    networks:
      - saga-net

  seat-service-db:
    image: postgres:17.5-bullseye
    container_name: seat-service-db
    environment:
      POSTGRES_USER: itpusr
      POSTGRES_PASSWORD: itp@168
      DATABASE_NAME: seatdb
    ports:
      - "6168:5432"
    volumes:
      - ./init_scripts/seat_postgres_init.sql:/docker-entrypoint-initdb.d/seat_postgres_init.sql
      - seat-service-postgres-vol:/var/lib/postgresql/data
    networks:
      - saga-net    

  payment-service-db:
    image: postgres:17.5-bullseye
    container_name: payment-service-db
    environment:
      POSTGRES_USER: itpusr
      POSTGRES_PASSWORD: itp@168
      DATABASE_NAME: paymentdb
    ports:
      - "7168:5432"
    volumes:
      - ./init_scripts/payment_postgres_init.sql:/docker-entrypoint-initdb.d/payment_postgres_init.sql
      - payment-service-postgres-vol:/var/lib/postgresql/data
    networks:
      - saga-net    


volumes:
  booking-service-postgres-vol:
  seat-service-postgres-vol:
  payment-service-postgres-vol:
  kafka_data:
     
networks:
  saga-net:
    external: true     
      